apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.image.repolitory }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.image.repolitory }}-{{ .Values.image.tag }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replica.count }}
  selector:
    matchLabels:
      app: {{ .Values.image.repolitory }}
      tag: {{ .Values.image.tag }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.image.repolitory }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.repolitory }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pull.policy }}
        name: {{ .Values.image.repolitory }}-{{ .Values.image.tag }}
